import { DatabaseState } from './types';

export const initialFactoryData: DatabaseState = {
  rawMaterials: [
    {
      id: 'rm-1',
      name: 'Corn (جواری / جوارت زرد درجه یک قندهار)',
      category: 'Grains',
      stockKg: 18500,
      unitPrice: 24, // 24 AFN per kg
      supplierId: 'sup-1',
      supplierName: 'حاجی بشیر احمد (غله جات قندهار)',
      dateAdded: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
      notes: 'دانه جواری درجه یک زرد خشک شده با رطوبت ۱۲٪',
      lowStockThreshold: 5000,
    },
    {
      id: 'rm-2',
      name: 'Soybean Meal (کنجاره سویای برازیلی وارداتی هرات)',
      category: 'Protein',
      stockKg: 11200,
      unitPrice: 48,
      supplierId: 'sup-2',
      supplierName: 'شرکت بازرگانی شمس هرات',
      dateAdded: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
      notes: 'پروتین ۴۶ فیصد وارداتی درجه یک',
      lowStockThreshold: 4000,
    },
    {
      id: 'rm-3',
      name: 'Oil Cake (کنجاره پنبه دانه / پخته بلخ باستان)',
      category: 'Protein',
      stockKg: 7800,
      unitPrice: 32,
      supplierId: 'sup-3',
      supplierName: 'تولیدی روغن و کنجاره مزار شریف',
      dateAdded: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
      notes: 'کنجاره میده شده با پروتین بالا و بدون ناخالصی',
      lowStockThreshold: 3000,
    },
    {
      id: 'rm-4',
      name: 'Petrol & Diesel Oil (تیل دیزل جنراتور و موتر فابریکه)',
      category: 'Fuel',
      stockKg: 1800, // Liters / Kg
      unitPrice: 65,
      supplierId: 'sup-4',
      supplierName: 'تانک تیل برادران احمدی',
      dateAdded: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
      notes: 'دیزل سوپر بدون دود برای جنراتور پرکینز ۳۰۰ کیلووات',
      lowStockThreshold: 500,
    },
    {
      id: 'rm-5',
      name: 'Wheat Bran (سبوس گندم اعلا آسیاب)',
      category: 'Fiber',
      stockKg: 6200,
      unitPrice: 18,
      supplierId: 'sup-1',
      supplierName: 'حاجی بشیر احمد (غله جات قندهار)',
      dateAdded: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
      notes: 'سبوس درشت با فیبر بالا مخصوص هضم',
      lowStockThreshold: 2000,
    },
    {
      id: 'rm-6',
      name: 'Premix & Vitamins (پری‌میکس ۲.۵٪ و ویتامین مرغداری)',
      category: 'Supplements',
      stockKg: 1450,
      unitPrice: 120,
      supplierId: 'sup-2',
      supplierName: 'شرکت بازرگانی شمس هرات',
      dateAdded: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
      notes: 'مکمل ویتامینه ۲.۵ فیصد مخصوص جوجه گوشتی با اسید آمینه‌ها',
      lowStockThreshold: 500,
    },
    {
      id: 'rm-7',
      name: 'Limestone Powder (پودر سنگ کلسیم هلمند / چونې پوډر)',
      category: 'Supplements',
      stockKg: 5200,
      unitPrice: 6,
      supplierId: 'sup-3',
      supplierName: 'تولیدی روغن و کنجاره مزار شریف',
      dateAdded: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
      notes: 'منبع کلسیم ۳۸٪ جهت استحکام استخوان و پوسته تخم مرغ',
      lowStockThreshold: 1000,
    },
    {
      id: 'rm-8',
      name: 'DCP - Dicalcium Phosphate (دی‌کلسیم فسفات فسفر دار)',
      category: 'Supplements',
      stockKg: 1900,
      unitPrice: 75,
      supplierId: 'sup-2',
      supplierName: 'شرکت بازرگانی شمس هرات',
      dateAdded: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
      notes: 'دی کلسیم فسفات ۱۸ فیصد فسفر خالص و ۲۴ فیصد کلسیم',
      lowStockThreshold: 500,
    },
    {
      id: 'rm-9',
      name: 'Fish Meal (پودر ماهی ۶۰٪ خلیج)',
      category: 'Protein',
      stockKg: 2800,
      unitPrice: 95,
      supplierId: 'sup-5',
      supplierName: 'مرکز واردات بیطار و خوراک طیور نیمروز',
      dateAdded: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
      notes: 'پودر ماهی خالص با پروتین ۶۰٪ و اسید آمینه غنی',
      lowStockThreshold: 800,
    },
    {
      id: 'rm-10',
      name: 'Salt & Mineral Premix (نمک یددار و منرال میده)',
      category: 'Supplements',
      stockKg: 3100,
      unitPrice: 12,
      supplierId: 'sup-1',
      supplierName: 'حاجی بشیر احمد (غله جات قندهار)',
      dateAdded: new Date(Date.now() - 8 * 86400000).toISOString().split('T')[0],
      notes: 'نمک مخصوص تغذیه حیوانات و طیور بدون ناخالصی',
      lowStockThreshold: 1000,
    }
  ],

  processedStock: [
    {
      id: 'ps-1',
      name: 'Broiler Starter Feed (دانه پیش‌دان سوپر گوشتی المکه)',
      formulaId: 'form-1',
      stockKg: 12400, // 248 bags of 50kg
      averageCostPerKg: 32.8,
      lastUpdated: new Date().toISOString().split('T')[0],
    },
    {
      id: 'ps-2',
      name: 'Broiler Grower Feed (دانه میان‌دان گوشتی اعلا)',
      formulaId: 'form-2',
      stockKg: 16500, // 330 bags
      averageCostPerKg: 30.5,
      lastUpdated: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    },
    {
      id: 'ps-3',
      name: 'Broiler Finisher Feed (دانه پس‌دان پرواری)',
      formulaId: 'form-3',
      stockKg: 8500, // 170 bags
      averageCostPerKg: 28.9,
      lastUpdated: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    },
    {
      id: 'ps-4',
      name: 'Layer Mash Feed (دانه مرغ تخم‌گذار سوپر فرمول)',
      formulaId: 'form-4',
      stockKg: 9200, // 184 bags
      averageCostPerKg: 27.2,
      lastUpdated: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    }
  ],

  suppliers: [
    {
      id: 'sup-1',
      name: 'حاجی بشیر احمد (غله جات قندهار)',
      phone: '0700 234 567',
      address: 'قندهار، مندی غله جات، دکان نمبر ۴۵',
      totalPurchasedAmount: 850000,
      totalPaid: 650000,
      balanceOwed: 200000, // We owe them 200k AFN
      createdAt: '2025-01-10',
      transactions: [
        {
          id: 'stx-1',
          date: '2026-03-01',
          type: 'purchase',
          description: 'خرید ۲۰ تن دانه جواری زرد',
          amount: 480000,
          paidAmount: 300000,
          remainingAmount: 180000,
          handledBy: 'حاجی صاحب (مالک اول)',
        },
        {
          id: 'stx-2',
          date: '2026-03-15',
          type: 'payment',
          description: 'تصفیه بخشی از طلبات جواری از طریق صرافی کابل',
          amount: 150000,
          paidAmount: 150000,
          remainingAmount: 0,
          handledBy: 'شریک صاحب (مالک دوم)',
        }
      ],
    },
    {
      id: 'sup-2',
      name: 'شرکت بازرگانی شمس هرات',
      phone: '0799 876 543',
      address: 'هرات، سرک ولایت، مارکیت واردات تجارتی',
      totalPurchasedAmount: 980000,
      totalPaid: 820000,
      balanceOwed: 160000,
      createdAt: '2025-01-15',
      transactions: [
        {
          id: 'stx-3',
          date: '2026-03-05',
          type: 'purchase',
          description: 'خرید ۱۰ تن کنجاره سویا و ۲ تن پری‌میکس ویتامینه',
          amount: 720000,
          paidAmount: 600000,
          remainingAmount: 120000,
          handledBy: 'حاجی صاحب (مالک اول)',
        }
      ],
    },
    {
      id: 'sup-3',
      name: 'تولیدی روغن و کنجاره مزار شریف',
      phone: '0786 112 233',
      address: 'مزار شریف، شهرک صنعتی بلخ، کوچه ۳',
      totalPurchasedAmount: 420000,
      totalPaid: 350000,
      balanceOwed: 70000,
      createdAt: '2025-02-01',
      transactions: [
        {
          id: 'stx-4',
          date: '2026-03-10',
          type: 'purchase',
          description: 'خرید ۸ تن کنجاره پنبه دانه میده',
          amount: 256000,
          paidAmount: 200000,
          remainingAmount: 56000,
          handledBy: 'شریک صاحب (مالک دوم)',
        }
      ],
    },
    {
      id: 'sup-4',
      name: 'تانک تیل برادران احمدی',
      phone: '0777 445 566',
      address: 'سرک عمومی جلال آباد، جوار شهرک صنعتی',
      totalPurchasedAmount: 195000,
      totalPaid: 195000,
      balanceOwed: 0,
      createdAt: '2025-02-10',
      transactions: [
        {
          id: 'stx-5',
          date: '2026-03-18',
          type: 'purchase',
          description: '۳۰۰۰ لیتر دیزل سوپر برای جنراتور فابریکه',
          amount: 195000,
          paidAmount: 195000,
          remainingAmount: 0,
          handledBy: 'ریان (Rayan)',
        }
      ],
    },
    {
      id: 'sup-5',
      name: 'مرکز واردات بیطار و خوراک طیور نیمروز',
      phone: '0708 654 321',
      address: 'زرنج نیمروز، گمرک تجارتی پل ابریشم',
      totalPurchasedAmount: 380000,
      totalPaid: 300000,
      balanceOwed: 80000,
      createdAt: '2025-03-01',
      transactions: [
        {
          id: 'stx-6',
          date: '2026-03-20',
          type: 'purchase',
          description: 'خرید ۴ تن پودر ماهی خالص ۶۰٪ خلیج',
          amount: 380000,
          paidAmount: 300000,
          remainingAmount: 80000,
          handledBy: 'حاجی صاحب (مالک اول)',
        }
      ],
    }
  ],

  customers: [
    {
      id: 'cust-1',
      name: 'فارم مرغداری برکت (حاجی نقیب الله)',
      phone: '0700 554 433',
      address: 'کابل، ولسوالی ده سبز، قریه بگرام',
      totalPurchasedAmount: 920000,
      totalPaid: 750000,
      balanceOwed: 170000, // Customer owes us 170k AFN
      createdAt: '2025-01-20',
      transactions: [
        {
          id: 'ctx-1',
          date: '2026-03-12',
          type: 'sale',
          description: 'فروش ۱۵۰ بوجی دانه پیش‌دان گوشتی',
          amount: 367500,
          paidAmount: 250000,
          remainingAmount: 117500,
          handledBy: 'ریان (Rayan)',
        },
        {
          id: 'ctx-2',
          date: '2026-03-22',
          type: 'payment_received',
          description: 'تصفیه نقدی در دفتر کارخانه المکه',
          amount: 100000,
          paidAmount: 100000,
          remainingAmount: 0,
          handledBy: 'حاجی صاحب (مالک اول)',
        }
      ],
    },
    {
      id: 'cust-2',
      name: 'فارم مرغداری پگاه هرات (انجینر عزیز)',
      phone: '0799 112 244',
      address: 'هرات، ولسوالی انجیل، شهرک صفا',
      totalPurchasedAmount: 640000,
      totalPaid: 500000,
      balanceOwed: 140000,
      createdAt: '2025-02-05',
      transactions: [
        {
          id: 'ctx-3',
          date: '2026-03-14',
          type: 'sale',
          description: 'فروش ۱۰۰ بوجی دانه میان‌دان',
          amount: 238000,
          paidAmount: 150000,
          remainingAmount: 88000,
          handledBy: 'شریک صاحب (مالک دوم)',
        }
      ],
    },
    {
      id: 'cust-3',
      name: 'فارم تخم‌گذار قندهار صفا (ملک عبدالحکیم)',
      phone: '0730 667 788',
      address: 'قندهار، دند، سرک شاهراه سپین بولدک',
      totalPurchasedAmount: 480000,
      totalPaid: 480000,
      balanceOwed: 0,
      createdAt: '2025-02-15',
      transactions: [
        {
          id: 'ctx-4',
          date: '2026-03-18',
          type: 'sale',
          description: 'فروش ۱۲۰ بوجی دانه مرغ تخم‌گذار سوپر',
          amount: 264000,
          paidAmount: 264000,
          remainingAmount: 0,
          handledBy: 'ریان (Rayan)',
        }
      ],
    },
    {
      id: 'cust-4',
      name: 'مرغداری بلخ باستان (حاجی شیر احمد)',
      phone: '0788 334 455',
      address: 'مزارشریف، ولسوالی دهدادی، روبروی دانشگاه',
      totalPurchasedAmount: 350000,
      totalPaid: 280000,
      balanceOwed: 70000,
      createdAt: '2025-03-01',
      transactions: [
        {
          id: 'ctx-5',
          date: '2026-03-24',
          type: 'sale',
          description: 'فروش ۶۰ بوجی دانه پیش‌دان و ۴۰ بوجی پس‌دان',
          amount: 239000,
          paidAmount: 180000,
          remainingAmount: 59000,
          handledBy: 'حاجی صاحب (مالک اول)',
        }
      ],
    }
  ],

  formulas: [
    {
      id: 'form-1',
      name: 'Broiler Starter Super Feed (دان پیش‌دان گوشتی سوپر - ۱ الی ۱۴ روزگی)',
      description: 'فرمول علمی با پروتین ۲۳٪ و انرژی ۳۰۰۰ کیلوکالری، مخصوص رشد سریع جوجه یک‌روزه',
      totalWeightKg: 1000,
      totalBatchCost: 32800,
      costPerKg: 32.8,
      createdDate: '2026-02-10',
      ingredients: [
        { rawMaterialId: 'rm-1', rawMaterialName: 'Corn (جواری زرد)', weightKg: 540, costPerKg: 24, totalCost: 12960 },
        { rawMaterialId: 'rm-2', rawMaterialName: 'Soybean Meal (کنجاره سویا)', weightKg: 320, costPerKg: 48, totalCost: 15360 },
        { rawMaterialId: 'rm-9', rawMaterialName: 'Fish Meal (پودر ماهی ۶۰٪)', weightKg: 40, costPerKg: 95, totalCost: 3800 },
        { rawMaterialId: 'rm-6', rawMaterialName: 'Premix & Vitamins (پری‌میکس ۲.۵٪)', weightKg: 25, costPerKg: 120, totalCost: 3000 },
        { rawMaterialId: 'rm-7', rawMaterialName: 'Limestone Powder (پودر کلسیم)', weightKg: 15, costPerKg: 6, totalCost: 90 },
        { rawMaterialId: 'rm-8', rawMaterialName: 'DCP (دی کلسیم فسفات)', weightKg: 15, costPerKg: 75, totalCost: 1125 },
        { rawMaterialId: 'rm-10', rawMaterialName: 'Salt (نمک میده)', weightKg: 5, costPerKg: 12, totalCost: 60 },
        { rawMaterialId: 'rm-5', rawMaterialName: 'Wheat Bran (سبوس گندم)', weightKg: 40, costPerKg: 18, totalCost: 720 },
      ],
    },
    {
      id: 'form-2',
      name: 'Broiler Grower Feed (دان میان‌دان گوشتی اعلا - ۱۵ الی ۲۸ روزگی)',
      description: 'فرمول متوازن با پروتین ۲۰.۵٪ و انرژی ۳۱۵۰ کیلوکالری برای وزن‌گیری استخوان و عضله',
      totalWeightKg: 1000,
      totalBatchCost: 30500,
      costPerKg: 30.5,
      createdDate: '2026-02-12',
      ingredients: [
        { rawMaterialId: 'rm-1', rawMaterialName: 'Corn (جواری زرد)', weightKg: 580, costPerKg: 24, totalCost: 13920 },
        { rawMaterialId: 'rm-2', rawMaterialName: 'Soybean Meal (کنجاره سویا)', weightKg: 270, costPerKg: 48, totalCost: 12960 },
        { rawMaterialId: 'rm-3', rawMaterialName: 'Oil Cake (کنجاره پنبه دانه)', weightKg: 60, costPerKg: 32, totalCost: 1920 },
        { rawMaterialId: 'rm-6', rawMaterialName: 'Premix & Vitamins (پری‌میکس ۲.۵٪)', weightKg: 25, costPerKg: 120, totalCost: 3000 },
        { rawMaterialId: 'rm-7', rawMaterialName: 'Limestone Powder (پودر کلسیم)', weightKg: 15, costPerKg: 6, totalCost: 90 },
        { rawMaterialId: 'rm-8', rawMaterialName: 'DCP (دی کلسیم فسفات)', weightKg: 12, costPerKg: 75, totalCost: 900 },
        { rawMaterialId: 'rm-10', rawMaterialName: 'Salt (نمک میده)', weightKg: 4, costPerKg: 12, totalCost: 48 },
        { rawMaterialId: 'rm-5', rawMaterialName: 'Wheat Bran (سبوس گندم)', weightKg: 34, costPerKg: 18, totalCost: 612 },
      ],
    },
    {
      id: 'form-3',
      name: 'Broiler Finisher Feed (دان پس‌دان پرواری - ۲۹ روزگی تا کشتار)',
      description: 'فرمول اقتصادی با پروتین ۱۸.۵٪ و انرژی بالا برای پرواربندی سریع و خوش‌طعمی گوشت',
      totalWeightKg: 1000,
      totalBatchCost: 28900,
      costPerKg: 28.9,
      createdDate: '2026-02-15',
      ingredients: [
        { rawMaterialId: 'rm-1', rawMaterialName: 'Corn (جواری زرد)', weightKg: 620, costPerKg: 24, totalCost: 14880 },
        { rawMaterialId: 'rm-2', rawMaterialName: 'Soybean Meal (کنجاره سویا)', weightKg: 220, costPerKg: 48, totalCost: 10560 },
        { rawMaterialId: 'rm-3', rawMaterialName: 'Oil Cake (کنجاره پنبه دانه)', weightKg: 80, costPerKg: 32, totalCost: 2560 },
        { rawMaterialId: 'rm-6', rawMaterialName: 'Premix & Vitamins (پری‌میکس ۲.۵٪)', weightKg: 20, costPerKg: 120, totalCost: 2400 },
        { rawMaterialId: 'rm-7', rawMaterialName: 'Limestone Powder (پودر کلسیم)', weightKg: 16, costPerKg: 6, totalCost: 96 },
        { rawMaterialId: 'rm-8', rawMaterialName: 'DCP (دی کلسیم فسفات)', weightKg: 10, costPerKg: 75, totalCost: 750 },
        { rawMaterialId: 'rm-10', rawMaterialName: 'Salt (نمک میده)', weightKg: 4, costPerKg: 12, totalCost: 48 },
        { rawMaterialId: 'rm-5', rawMaterialName: 'Wheat Bran (سبوس گندم)', weightKg: 30, costPerKg: 18, totalCost: 540 },
      ],
    }
  ],

  productionBatches: [
    {
      id: 'pb-1',
      formulaId: 'form-1',
      formulaName: 'Broiler Starter Super Feed (دان پیش‌دان گوشتی)',
      date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
      totalWeightKg: 5000,
      costPerKg: 32.8,
      totalCost: 164000,
      operatorName: 'انجینر ریان (Rayan)',
      notes: 'تولید شیفت صبح - ۱۰۰ بوجی ۵۰ کیلویی با کیفیت عالی',
    },
    {
      id: 'pb-2',
      formulaId: 'form-2',
      formulaName: 'Broiler Grower Feed (دان میان‌دان گوشتی اعلا)',
      date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
      totalWeightKg: 8000,
      costPerKg: 30.5,
      totalCost: 244000,
      operatorName: 'استاد احمدالله (مسئول آسیاب و مکسر)',
      notes: 'تولید پلت شده با مکسر صنعتی ۵ تنی',
    },
    {
      id: 'pb-3',
      formulaId: 'form-3',
      formulaName: 'Broiler Finisher Feed (دان پس‌دان پرواری)',
      date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
      totalWeightKg: 6000,
      costPerKg: 28.9,
      totalCost: 173400,
      operatorName: 'انجینر ریان (Rayan)',
      notes: 'تولید ۱۲۰ بوجی آماده انتقال به گدام فروشات',
    }
  ],

  sales: [
    {
      id: 'sale-1',
      date: new Date().toISOString().split('T')[0],
      customerId: 'cust-1',
      customerName: 'فارم مرغداری برکت (حاجی نقیب الله)',
      customerPhone: '0700 554 433',
      productId: 'ps-1',
      productName: 'Broiler Starter Feed (دانه پیش‌دان سوپر گوشتی المکه)',
      unitType: 'bag',
      unitQuantity: 100,
      quantityKg: 5000,
      salePricePerUnit: 2450,
      totalAmount: 245000,
      costRatePerKg: 32.8,
      totalCostOfGoods: 164000,
      profit: 81000,
      paidAmount: 200000,
      remainingAmount: 45000,
      notes: '۱۰۰ بوجی ۵۰ کیلویی - ۴۵ هزار افغانی باقی‌داری',
    },
    {
      id: 'sale-2',
      date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
      customerId: 'cust-2',
      customerName: 'فارم مرغداری پگاه هرات (انجینر عزیز)',
      customerPhone: '0799 112 244',
      productId: 'ps-2',
      productName: 'Broiler Grower Feed (دانه میان‌دان گوشتی اعلا)',
      unitType: 'bag',
      unitQuantity: 80,
      quantityKg: 4000,
      salePricePerUnit: 2380,
      totalAmount: 190400,
      costRatePerKg: 30.5,
      totalCostOfGoods: 122000,
      profit: 68400,
      paidAmount: 150000,
      remainingAmount: 40400,
      notes: 'ارسال با موتر باربری به هرات',
    },
    {
      id: 'sale-3',
      date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
      customerId: 'cust-3',
      customerName: 'فارم تخم‌گذار قندهار صفا (ملک عبدالحکیم)',
      customerPhone: '0730 667 788',
      productId: 'ps-4',
      productName: 'Layer Mash Feed (دانه مرغ تخم‌گذار سوپر)',
      unitType: 'bag',
      unitQuantity: 120,
      quantityKg: 6000,
      salePricePerUnit: 2200,
      totalAmount: 264000,
      costRatePerKg: 27.2,
      totalCostOfGoods: 163200,
      profit: 100800,
      paidAmount: 264000,
      remainingAmount: 0,
      notes: 'تصفیه کامل نقدی در لحظه بارگیری',
    }
  ],

  expenses: [
    {
      id: 'exp-1',
      date: new Date().toISOString().split('T')[0],
      category: 'fuel',
      description: 'خرید تیل دیزل سوپر جهت روشن نگهداشتن جنراتور فابریکه',
      amount: 19500,
      paidBy: 'مسئول اداری و مالی',
      notes: 'فاکتور تانک تیل برادران احمدی',
    },
    {
      id: 'exp-2',
      date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
      category: 'salary',
      description: 'معاش هفته‌وار کارگران خط پروسس، آسیاب و بارگیری',
      amount: 45000,
      paidBy: 'ریان (Rayan)',
      notes: '۶ نفر پرسونل فنی و باربری',
    },
    {
      id: 'exp-3',
      date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
      category: 'maintenance',
      description: 'تعویض چکش‌های آسیاب و گریس کاری بلبرینگ‌های مکسر صنعتی',
      amount: 14000,
      paidBy: 'استاد احمدالله',
      notes: 'خرید وسایل از مارکیت ماشین‌آلات کابل',
    },
    {
      id: 'exp-4',
      date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
      category: 'electricity',
      description: 'پرداخت بل برق صنعتی سه فاز د افغانستان برشنا شرکت',
      amount: 32000,
      paidBy: 'حسابدار کارخانه',
      notes: 'دوره ماه حوت',
    }
  ],

  cashInHand: 540000, // 540,000 AFN cash balance
};
